global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    follow_redirects: true
    static_configs:
      - targets: ["sentiment-analysis:8000"] 
    scrape_timeout: 10s
    honor_labels: true

rule_files:
  - "alert_rules.yml" 
